// =======================================================
// UltraRealistic Engine Rendering Pipeline (UERP)
// Core 3D Graphics Library
// File: UERP.cpp
// Language: C++17
// =======================================================

#include <vector>
#include <string>
#include <cmath>
#include <iostream>
#include <memory>

namespace UERP {

// =======================================================
// Math Core
// =======================================================

struct Vec3 {
    float x, y, z;

        Vec3() : x(0), y(0), z(0) {}
            Vec3(float X, float Y, float Z) : x(X), y(Y), z(Z) {}

                Vec3 operator+(const Vec3& v) const {
                        return Vec3(x + v.x, y + v.y, z + v.z);
                            }

                                Vec3 operator-(const Vec3& v) const {
                                        return Vec3(x - v.x, y - v.y, z - v.z);
                                            }

                                                Vec3 operator*(float s) const {
                                                        return Vec3(x * s, y * s, z * s);
                                                            }
                                                            };

                                                            struct Mat4 {
                                                                float m[16];

                                                                    static Mat4 Identity() {
                                                                            Mat4 r{};
                                                                                    for (int i = 0; i < 16; i++)
                                                                                                r.m[i] = (i % 5 == 0) ? 1.0f : 0.0f;
                                                                                                        return r;
                                                                                                            }

                                                                                                                static Mat4 Perspective(float fov, float aspect, float nearP, float farP) {
                                                                                                                        Mat4 r{};
                                                                                                                                float t = tanf(fov * 0.5f);
                                                                                                                                        r.m[0]  = 1.0f / (aspect * t);
                                                                                                                                                r.m[5]  = 1.0f / t;
                                                                                                                                                        r.m[10] = -(farP + nearP) / (farP - nearP);
                                                                                                                                                                r.m[11] = -1.0f;
                                                                                                                                                                        r.m[14] = -(2.0f * farP * nearP) / (farP - nearP);
                                                                                                                                                                                return r;
                                                                                                                                                                                    }
                                                                                                                                                                                    };

                                                                                                                                                                                    // =======================================================
                                                                                                                                                                                    // GPU Abstraction Layer
                                                                                                                                                                                    // =======================================================

                                                                                                                                                                                    class GPUBuffer {
                                                                                                                                                                                    public:
                                                                                                                                                                                        virtual void Upload(void* data, size_t size) = 0;
                                                                                                                                                                                        };

                                                                                                                                                                                        class GPUShader {
                                                                                                                                                                                        public:
                                                                                                                                                                                            virtual void Bind() = 0;
                                                                                                                                                                                            };

                                                                                                                                                                                            class GPURenderDevice {
                                                                                                                                                                                            public:
                                                                                                                                                                                                virtual void DrawIndexed(int indexCount) = 0;
                                                                                                                                                                                                };

                                                                                                                                                                                                // =======================================================
                                                                                                                                                                                                // Mesh System
                                                                                                                                                                                                // =======================================================

                                                                                                                                                                                                struct Vertex {
                                                                                                                                                                                                    Vec3 position;
                                                                                                                                                                                                        Vec3 normal;
                                                                                                                                                                                                            Vec3 uv;
                                                                                                                                                                                                            };

                                                                                                                                                                                                            class Mesh {
                                                                                                                                                                                                            public:
                                                                                                                                                                                                                std::vector<Vertex> vertices;
                                                                                                                                                                                                                    std::vector<uint32_t> indices;

                                                                                                                                                                                                                        std::unique_ptr<GPUBuffer> vertexBuffer;
                                                                                                                                                                                                                            std::unique_ptr<GPUBuffer> indexBuffer;

                                                                                                                                                                                                                                void UploadToGPU() {
                                                                                                                                                                                                                                        if (vertexBuffer)
                                                                                                                                                                                                                                                    vertexBuffer->Upload(vertices.data(),
                                                                                                                                                                                                                                                                    vertices.size() * sizeof(Vertex));

                                                                                                                                                                                                                                                                            if (indexBuffer)
                                                                                                                                                                                                                                                                                        indexBuffer->Upload(indices.data(),
                                                                                                                                                                                                                                                                                                        indices.size() * sizeof(uint32_t));
                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                                                                            // =======================================================
                                                                                                                                                                                                                                                                                                            // Material & Shading
                                                                                                                                                                                                                                                                                                            // =======================================================

                                                                                                                                                                                                                                                                                                            class Material {
                                                                                                                                                                                                                                                                                                            public:
                                                                                                                                                                                                                                                                                                                Vec3 albedo;
                                                                                                                                                                                                                                                                                                                    float roughness;
                                                                                                                                                                                                                                                                                                                        float metallic;

                                                                                                                                                                                                                                                                                                                            std::unique_ptr<GPUShader> shader;

                                                                                                                                                                                                                                                                                                                                Material()
                                                                                                                                                                                                                                                                                                                                        : albedo(1, 1, 1), roughness(0.5f), metallic(0.0f) {}

                                                                                                                                                                                                                                                                                                                                            void Bind() {
                                                                                                                                                                                                                                                                                                                                                    if (shader)
                                                                                                                                                                                                                                                                                                                                                                shader->Bind();
                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                                                                                                                                    // =======================================================
                                                                                                                                                                                                                                                                                                                                                                    // Camera System
                                                                                                                                                                                                                                                                                                                                                                    // =======================================================

                                                                                                                                                                                                                                                                                                                                                                    class Camera {
                                                                                                                                                                                                                                                                                                                                                                    public:
                                                                                                                                                                                                                                                                                                                                                                        Vec3 position;
                                                                                                                                                                                                                                                                                                                                                                            Vec3 rotation;

                                                                                                                                                                                                                                                                                                                                                                                float fov = 70.0f;
                                                                                                                                                                                                                                                                                                                                                                                    float nearPlane = 0.1f;
                                                                                                                                                                                                                                                                                                                                                                                        float farPlane  = 1000.0f;

                                                                                                                                                                                                                                                                                                                                                                                            Mat4 GetProjection(float aspect) const {
                                                                                                                                                                                                                                                                                                                                                                                                    return Mat4::Perspective(
                                                                                                                                                                                                                                                                                                                                                                                                                fov * 3.14159f / 180.0f,
                                                                                                                                                                                                                                                                                                                                                                                                                            aspect,
                                                                                                                                                                                                                                                                                                                                                                                                                                        nearPlane,
                                                                                                                                                                                                                                                                                                                                                                                                                                                    farPlane
                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                // =======================================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Scene Graph
                                                                                                                                                                                                                                                                                                                                                                                                                                                                // =======================================================

                                                                                                                                                                                                                                                                                                                                                                                                                                                                class Entity {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                public:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Vec3 position;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Vec3 rotation;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Vec3 scale{1,1,1};

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Mesh* mesh = nullptr;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Material* material = nullptr;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    class Scene {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    public:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        std::vector<Entity> entities;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Camera camera;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // =======================================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Renderer Core
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // =======================================================

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            class Renderer {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            private:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                GPURenderDevice* device;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                public:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Renderer(GPURenderDevice* dev) : device(dev) {}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        void Render(Scene& scene) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for (auto& e : scene.entities) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (!e.mesh || !e.material)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            continue;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        e.material->Bind();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    e.mesh->UploadToGPU();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                device->DrawIndexed(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                static_cast<int>(e.mesh->indices.size())
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // =======================================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Engine Entry (Library Test Hook)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // =======================================================

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        void InitializeUERP() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            std::cout << "UERP initialized: UltraRealistic 3D Pipeline\n";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } // namespace UERP